name: shrine
description: Learn how to use Material for structure and layout.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  google_fonts: ^2.3.2
  cupertino_icons: ^1.0.3
  shrine_images: ^2.0.1
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.15
  provider: ^6.0.2
  adaptive_theme: ^2.2.0
  firebase_storage: ^10.2.16
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  # TODO: Insert Fonts (103)
  uses-material-design: true
  assets:
    - assets/diamond.png
  fonts:
    - family: Yrsa
      fonts:
        - asset: assets/Yrsa-VariableFont_wght.ttf
